name: Deploy Lambda

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'    # Updated to Node.js 18.x
          
      - name: Install dependencies
        run: npm install
        
      - name: Create deployment package
        run: |
          zip -r function.zip ./* -x '*.git*'
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
        

          
      - name: Deploy to Lambda
        run: |
          # Update function code
          aws lambda update-function-code \
            --function-name auto-tweet \
            --zip-file fileb://function.zip

          # Update function configuration with environment variables
          aws lambda update-function-configuration \
            --function-name auto-tweet \
            --environment "Variables={
              TWITTER_API_KEY=${{ secrets.TWITTER_API_KEY }},
              TWITTER_API_SECRET=${{ secrets.TWITTER_API_SECRET }},
              TWITTER_ACCESS_TOKEN=${{ secrets.TWITTER_ACCESS_TOKEN }},
              TWITTER_ACCESS_SECRET=${{ secrets.TWITTER_ACCESS_SECRET }},
              OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            }"

      - name: Create CloudWatch Event Rule
        run: |
          # Create or update the rule
          aws events put-rule \
            --name "AutoTweetSchedule" \
            --schedule-expression "cron(* 4 * * ? *)" \
            --state ENABLED

          # Remove existing permission if it exists
          aws lambda remove-permission \
            --function-name auto-tweet \
            --statement-id "AllowEventBridgeInvoke" || true
          
          # Add new permission
          sleep 5  # Wait for removal to propagate
          aws lambda add-permission \
            --function-name auto-tweet \
            --statement-id "AllowEventBridgeInvoke" \
            --action 'lambda:InvokeFunction' \
            --principal events.amazonaws.com \
            --source-arn $(aws events describe-rule --name "AutoTweetSchedule" --query 'Arn' --output text)
          
          # Update the target
          aws events put-targets \
            --rule "AutoTweetSchedule" \
            --targets "Id"="1","Arn"="$(aws lambda get-function --function-name auto-tweet --query 'Configuration.FunctionArn' --output text)"
